Added the prepare for develop script with volume mapping
zeeguu-ecosystem/Lineup pull request #28
Opened 2019-11-21 13:05 UTC by mfurak

2019-11-21 13:09 UTC, mircealungu requested changes

2019-11-21 13:09 UTC, mircealungu commented on prepare_for_develop.sh
> +echo "you can make changes to Zeeguu-Web locally; then execute 'docker exec zeeguu-web-with-volume python ./Zeeguu-Web/setup.py develop' to deploy"
@mfurak this is cool.
can we move the `docker exec zeeguu-web-with-volume python ./Zeeguu-Web/setup.py develop` into it's own shell script? something entitled like: './redeploy_web.sh' or so? then the echo message becomes shorter.

2019-11-21 16:29 UTC, alinbalutoiu commented
There are a couple changes to ` Zeeguu-Teacher-Dashboard-React` which I'm not sure if they are intended to be committed.

You could also change the script `rebuild_web.sh` to `run_web_develop.sh` where you run all those commands. Instead of the `echo` you can also do `docker run -it --net=host <all args here> python ./Zeeguu-Web/setup.py develop` which will start the docker container and run the command directly.

2019-11-22 14:06 UTC, mircealungu commented on prepare_for_develop.sh
> +echo "you can make changes to Zeeguu-Web locally; then execute 'docker exec zeeguu-web-with-volume python ./Zeeguu-Web/setup.py develop' to deploy"
Also, shouldn't this script also do with zeeguu-api-core what it does with zeeguu-web?

2019-11-22 14:30 UTC, mircealungu commented
@mfurak : indeed, try to submit the PR without the changes to the Teacher-Dashboard. You seem to have retrieved the latest version of the Teacher-Dashboard-React locally in your lineup. However, you should normally keep the submodule versions that are published in the lineup when you submit PRs. (Ergo, don't recursivelly pull all submodules before sending a PR).

2019-11-26 11:47 UTC, mircealungu approved these changes
this finally works now

2019-11-26 11:47 UTC, merged